"""Initial

Revision ID: 7e9a8719f701
Revises: 
Create Date: 2022-09-14 14:27:29.481878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e9a8719f701'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_dt', sa.DATE(), nullable=True),
    sa.Column('views', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cpc', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('cpm', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
