version: '2'

services:
  statistics_counters_main:
    build: app
    command: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000 --worker=4
    env_file:
      - api.env
    ports:
      - "8000:8000"
    volumes:
      - /var/log/main:/logs
    restart: always
    networks:
      - backend

  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql-statistics-counters
    env_file:
      - mysql.env
    volumes:
      - mysql:/var/lib/mysql/data

volumes:
  mysql