version: '2'

services:
  statistics_counters_main:
    build: app
    command: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000
    env_file:
      - api.env
    environment:
      - LOCAL_CONFIG=CONFIG
    ports:
      - "8000:8000"
    volumes:
      - /var/log/main:/logs
    restart: always
    networks:
      - backend

  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql-statistics-counters
    env_file:
      - mysql.env
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
